#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SConstruct (Python)
# 
# Purpose: Test sflanda89tomo in a layers constant velocity model
# with picked (t0,m0) pairs.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programer: Rodolfo A C Neves (Dirack) 07/02/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Madagascar package
from rsf.proj import *

# Constant velocity model for stereoniptomo
Flow('model',None,
     '''
     spike n1=301 d1=0.01 o1=0 n2=1001 d2=0.01 o2=-2 mag=1.508 |
     put label1=Depth unit1=km label2=Position unit2=km
     ''' )

# plot the model
Plot('model','model','grey color=j scalebar=y label1=Depth unit1=km label2=Position unit2=km barlabel=Velocity barunit=km/s barreverse=y title="Constant Velocity Model" allpos=y')

# Points of the cubic spline velocity function
Flow('sza',None,'math n1=11 d1=1 o1=-2 output="1.0"')
Flow('szb',None,'math n1=11 d1=1 o1=-2 output="1.8"')
Flow('sz_2',['sza','szb'],
	'''
       rcat ${SOURCES[1]} axis=1 |
        put n1=22
	''')

sz='sz_2'
#sz='sza'
sv='sv_2'
Flow(sv,None,
	'''
	spike nsp=3 mag=%s k1=1,2,3 n1=3
	'''%('1.5,1.7,2.0'))

Flow('model2',['model','sz_2','sv_2'],
	'''
	buildmodel sz=${SOURCES[1]} vz=${SOURCES[2]}
	''')

Result('model2','grey title="Velocity model" color=j scalebar=y barreverse=y barunit=Km/s label1=Depth label2=Distance unit1=Km unit2=Km barlabel=Velocity allpos=y bias=1.5')

Result('splinevellayer','model2',
	'''
	window n1=1 f1=150 | graph label1=Distance label2=Velocity wanttitle=n
	''')
End()
