#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SConscript1 (Python)
# 
# Purpose: Setup input files for this test.
# 
# Site: https://dirack.github.io
# 
# Version 1.0
# 
# Programmer: Rodolfo A C Neves (Dirack) 06/03/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

from rsf.proj import *

Flow('t0s.asc','pick.txt',
	'''
	./ascFormat.sh ${TARGETS} 1
	''')

Flow('t0s','t0s.asc','dd type=float form=native | put n2=1 d2=1 o2=0')

Flow('m0s.asc','pick.txt',
	'''
	./ascFormat.sh ${TARGETS} 2
	''')

Flow('m0s','m0s.asc','dd type=float form=native | put n2=1 d2=1 o2=0')

Flow('rnips',['parametersCube','t0s','m0s'],
	'''
	window n1=1 f1=1 |
 	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]}
	''')

Flow('betas',['parametersCube','t0s','m0s'],
	'''
	window n1=1 f1=2 |
 	getparameter t0s=${SOURCES[1]} m0s=${SOURCES[2]}
	''')
